---
all:
  hosts:
    Leaf1:
      ansible_host: 192.168.100.200
    Leaf2:
      ansible_host: 192.168.100.201
    Leaf3:
      ansible_host: 192.168.100.202
    Leaf4:
      ansible_host: 192.168.100.205
    Spine1:
      ansible_host: 192.168.100.203
    Spine2:
      ansible_host: 192.168.100.204

eve-nxos-vxlan:
  hosts:
    Leaf1:
    Leaf2:
    Leaf3:
    Leaf4:
    Spine1:
    Spine2:

eve-nxos-vxlan-spines:
  hosts:
    Spine1:
    Spine2:

eve-nxos-vxlan-leafs:
  hosts:
    Leaf1:
    Leaf2:
    Leaf3:
    Leaf4:

leaf1-leaf2:
  hosts:
    Leaf1:
    Leaf2:


