---
management_gateway: 192.168.100.1
management_ip: 192.168.100.202
management_mask: /24

loopback_interfaces:
  - name: loopback0
    ip_address: 198.51.100.42
    mask: /32
    ospf_process_id: 1
    ospf_area: 0.0.0.0
    pim: sparse-mode
    enabled: true
  - name: loopback1
    ip_address: 192.51.100.45
    mask: /32
    ospf_process_id: 1
    ospf_area: 0.0.0.0
    pim: sparse-mode
    enabled: true

interfaces:
  - name: eth1/2
    ip_address: 192.168.13.2
    mask: /24
    ospf_process_id: 1
    ospf_area: 0.0.0.0
    pim: sparse-mode
    enabled: true
  - name: eth1/3
    ip_address: 192.168.23.2
    mask: /24
    ospf_process_id: 1
    ospf_area: 0.0.0.0
    pim: sparse-mode
    enabled: true

ospf:
  process_id: 1

pim:
  rp_address: 192.0.2.1
  group_list: 224.0.0/4