---
- name: Render configuration from template for Cisco NX-OS
  hosts: Leaf1
  gather_facts: false

  tasks:

    - name: Render config from template
      ansible.builtin.template:
        src: ../templates/nxos.j2
        dest: "../configs/{{ inventory_hostname }}.cfg"
      delegate_to: localhost
      register: render_result

    - name: Git add, commit and push
      block:
        - name: Add changes to git
          ansible.builtin.command: "git add ."
          args:
            chdir: ~/repositories/network
          delegate_to: localhost

        - name: Commit changes
          ansible.builtin.command: "git commit -m 'Automated configuration update via Ansible'"
          args:
            chdir: ~/repositories/network
          delegate_to: localhost
          register: commit_result    
          
        - name: Push changes to the remote repository
          ansible.builtin.command: "git push -u origin main" # Adjust 'origin main' as needed
          args:
            chdir: ~/repositories/network
          register: push_result
          when: commit_result is not failed and "nothing to commit" not in commit_result.stdout

        - name: Display commit and push results
          ansible.builtin.debug:
            msg: "{{ item.stdout }}"
          loop: "{{ [commit_result, push_result] }}"
          when: item is defined and item is not failed
      when: render_result.changed


    - name: Copy and merge device configuration
      block:
        - name: Ensure feature scp-server is enabled
          cisco.nxos.nxos_feature:
            feature: scp-server
            state: enabled

        - name: Copy config to device
          ansible.netcommon.net_put:
            src: "../configs/{{ inventory_hostname }}.cfg"
            dest: "bootflash:/{{ inventory_hostname }}.cfg"

        - name: Replace config
          cisco.nxos.nxos_config:
            replace_src: "bootflash:/{{ inventory_hostname }}.cfg"
            replace: config
            save_when: modified
      when: render_result.changed